export const campaignTypes = [
  "Inbound Customer Support Campaigns",
  "Outbound Sales & Lead Generation Campaigns",
  "Live Chat Support Campaigns",
  "Email Support & Ticket Handling Campaigns",
  "Technical Support Campaigns",
  "Back Office / KYC / Data Processing Campaigns",
];

export const executionFramework = [
  "Verified centre allocation",
  "Dedicated team leader and management support",
  "Daily attendance and productivity reporting",
  "Quality monitoring and audit reporting",
  "SLA tracking and escalation management",
  "Continuous training and improvement",
];

export const engagementModels = [
  "Dedicated Team Model",
  "Per Seat / Per Agent Model",
  "Hourly Outsourcing Model",
  "Per Ticket / Per Resolution Model",
];

export const liveProjectOpportunities = [
  {
    id: "telecom-inbound-eu",
    title: "Telecom Chat Support Project",
    code: "PG-TEL-6728",
    clientCode: "CL-778829",
    country: "Germany",
    countryFlag: "DE",
    seatsRequired: 24,
    lastActivity: "22 Feb 2026, 10:40 PM",
    goLiveDays: 7,
    image: "GP-31.jpg",
    channels: ["Live Chat", "Ticket Queue", "Escalation Desk"],
  },
  {
    id: "travel-support-nz",
    title: "Travel Chat Support",
    code: "PG-TRV-2677",
    clientCode: "CL-267762",
    country: "New Zealand",
    countryFlag: "NZ",
    seatsRequired: 9,
    lastActivity: "22 Feb 2026, 08:52 PM",
    goLiveDays: 8,
    image: "GP-33.jpg",
    channels: ["Chat Support", "Email Support"],
  },
  {
    id: "healthcare-chat-au",
    title: "Healthcare Chat Support",
    code: "PG-HLT-5452",
    clientCode: "CL-324123",
    country: "Australia",
    countryFlag: "AU",
    seatsRequired: 17,
    lastActivity: "21 Feb 2026, 11:20 PM",
    goLiveDays: 10,
    image: "GP-35.jpg",
    channels: ["Patient Query Desk", "Inbound Chat"],
  },
  {
    id: "kyc-voice-ro",
    title: "KYC Chat Support - Telecom",
    code: "PG-KYC-8942",
    clientCode: "CL-689201",
    country: "Romania",
    countryFlag: "RO",
    seatsRequired: 26,
    lastActivity: "21 Feb 2026, 08:11 PM",
    goLiveDays: 5,
    image: "GP-41.jpg",
    channels: ["Verification Queue", "Chat Compliance"],
  },
  {
    id: "banking-support-ca",
    title: "Banking Chat Support",
    code: "PG-BNK-2892",
    clientCode: "CL-773788",
    country: "Canada",
    countryFlag: "CA",
    seatsRequired: 59,
    lastActivity: "20 Feb 2026, 11:34 PM",
    goLiveDays: 14,
    image: "GP-42.jpg",
    channels: ["Secure Chat", "Dispute Desk", "Ticket Routing"],
  },
  {
    id: "fmcg-live-support-za",
    title: "FMCG Chat Support",
    code: "PG-FMCG-2718",
    clientCode: "CL-528820",
    country: "South Africa",
    countryFlag: "ZA",
    seatsRequired: 53,
    lastActivity: "20 Feb 2026, 08:41 PM",
    goLiveDays: 24,
    image: "GP-37.jpg",
    channels: ["Brand Care", "Order Status", "Retention Chat"],
  },
];

export const upcomingProjects = [
  {
    id: "crm-dev-01",
    title: "Custom CRM Development",
    projectId: "UP-CRM-8891",
    metaLabel: "Deadline",
    metaValue: "15 Mar 2026",
    category: "time",
    typeLabel: "Time-Based",
    image: "GP16.jpg",
  },
  {
    id: "lead-us-02",
    title: "Lead Generation Campaign - US Process",
    projectId: "UP-LED-5620",
    metaLabel: "Seats",
    metaValue: "30",
    category: "live",
    typeLabel: "Live Projects",
    image: "GP17.jpg",
  },
  {
    id: "fmcg-sales-03",
    title: "Product Sales Campaign - FMCG",
    projectId: "UP-FMCG-2054",
    metaLabel: "Deadline",
    metaValue: "20 Mar 2026",
    category: "instant",
    typeLabel: "Instant Allocation",
    image: "GP18.jpg",
  },
  {
    id: "seo-bugfix-04",
    title: "Website Bug Fix & SEO Optimization",
    projectId: "UP-SEO-7543",
    metaLabel: "Timeline",
    metaValue: "4 Weeks",
    category: "time",
    typeLabel: "Time-Based",
    image: "GP19.jpg",
  },
  {
    id: "ecommerce-app-05",
    title: "E-Commerce Mobile App (Android + iOS)",
    projectId: "UP-APP-9208",
    metaLabel: "Deadline",
    metaValue: "28 Mar 2026",
    category: "instant",
    typeLabel: "Instant Allocation",
    image: "GP20.jpg",
  },
];
